version: '3.1'
services:
  mongo:
    image: registry.azabu-juban.com/mongoose-mongo
    deploy:
      placement:
        constraints:
          - node.labels.type == mongo
  app:
    image: registry.azabu-juban.com/mongoose-app
    secrets:
      - s3_secrets_production
    depends_on:
      - mongo
    deploy:
      placement:
        constraints:
          - node.labels.type == app
  nginx:
    image: registry.azabu-juban.com/mongoose-nginx
    ports:
      - "80:80"
      - "443:443"
    deploy:
      placement:
        constraints:
          - node.labels.type == nginx

secrets:
  s3_secrets_production:
    external: true
